name = "nvim-portfolio"
pages_build_output_dir = ".vercel/output/static"
compatibility_date = "2026-01-29"
compatibility_flags = ["nodejs_compat"]

[env.preview]
compatibility_flags = ["nodejs_compat"]
